name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Clean Git History and Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Clean local tracking attributes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 2. Slice off all past commit histories
          git checkout --orphan temp_branch
          git add -A
          git commit -am "Deploy clean code release"
          
          # 3. Rename branch and push past the firewall
          git branch -M main
          git remote add hf https://SaugatXthaa:$HF_TOKEN@huggingface.co/spaces/SaugatXthaa/HerumHai
          git push hf main --force
